name: Back
main: Back\Back
version: 2.0
api: 
 [3.0.0]
load: STARTUP
author: Martin77Epic
description: Going to ur last Deathpoint
website: http://github.com/Martin77Epic/Back
commands:
 login:
  description: "Teleport to your last Death Postion"
  usage: "/back"
  permission: back.command

permissions:
   martin77epic.back:
    description: "Teleport to your last Death postion"
    default: true
